### ISSUE TITLE
Biamp Tesira product

### ISSUE THREAD

**Issue by ldemule** [bitfocus/companion-module-biamp-tesira#1]
Hello there !
Thanks a lot for your work !
I use companion to control small installation and I use to work with Biamp Tesira product to manage the audio part.
Is it possible to create a module to controle Biamp Tesira system with companion ?
Thank you

**Comment by timt-111** [comment]
@themusicnerd I think I've found a possible lead as to why things are not working (based on my testing using the audia module and looking at packet captures)

it seems that the telnet service on the biamp devices MUST negotiate options before allowing a connection.  I can see this negotation happening when I use something like PuTTY to connect and I do NOT see it happening when companion connects -- see this doc from biamp for a suggestion of having companion automatically decline these negotiations...
[](https://tesira-help.biamp.com/System_Control/Tesira_Text_Protocol/Telnet.htm)

**Comment by themusicnerd** [comment]
Wooo thanks so muich!
I have been sick for the last 3-4 weeks, so I'll have a go at sending these upon connect :)
Thanks so much for all that amazing information!

**Comment by timt-111** [comment]
Great to hear you're still interested in making this happen -- and hope you're feeling better!
If you are able to figure out the code, I'd love to help automate the negotiation in a more 'proper' way -- we'd have to read / parse the data coming back from the device and respond with the appropriate values to negotiate.  it would be even more fantastic to have this module provide feedback to companion based on its responses, or set up ability to subscribe to settings in tesira -- again, I'm happy to do some of this legwork, and help put together the logic - I'm not so great at the actual coding part.

**Comment by timt-111** [comment]
module is tested and basic functions working
